/*
 * ExitEntryForVisitor.java
 *
 * Created on October 12, 2013, 12:26 PM
 */

package visitorinformationsystem;
//import java.util.*;
import java.util.Date;
import java.text.*;
import java.sql.*;

/**
 *
 * @author  amit
 */
public class ExitEntryForVisitor extends javax.swing.JInternalFrame {
    Connection cn;
    ResultSet res;
     Statement st;

    /** Creates new form ExitEntryForVisitor */
    public ExitEntryForVisitor() {
        initComponents();
         try
              {
                  Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                  cn=DriverManager.getConnection("jdbc:odbc:ami","amit","amit");
                  st=cn.createStatement();
     
              }
        catch(Exception e)
              {
                  e.printStackTrace();
              }
        dateExit();
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        exitDate = new javax.swing.JTextField();
        exitTime = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Exit");

        jLabel2.setText("Pass Number");

        jLabel3.setText("Exit Date");

        jLabel4.setText("Exit Time");

        exitDate.setEditable(false);
        exitDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitDateActionPerformed(evt);
            }
        });

        exitTime.setEditable(false);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(exitTime)
                            .addComponent(exitDate)
                            .addComponent(passNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(exitDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(exitTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String eestr;
    String eestr1;
    public void dateExit()
    {
        Date date = new Date();
        SimpleDateFormat sdf;
        sdf=new SimpleDateFormat("dd-MM-yyyy");
	eestr=sdf.format(date);
        exitDate.setText(eestr);
        sdf=new SimpleDateFormat("hh:mm");
        eestr1=sdf.format(date);
        exitTime.setText(eestr1);
    }
private void exitDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitDateActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_exitDateActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    try {
     
    dateExit();
    
    res=st.executeQuery("select * from visitor where passno='"+passNumber.getText()+"'");
    
        if(res.next())
        {
        st.execute("update visitor set outdate='"+eestr+"',outtime='"+eestr1+"' where passno='"+passNumber.getText()+"'");
        javax.swing.JOptionPane.showMessageDialog(null,"Successfully Modified...");
        }
        else
        {
         javax.swing.JOptionPane.showMessageDialog(null,"Invalid...");
        }
        
    }
    catch(Exception e)
    {
        javax.swing.JOptionPane.showMessageDialog(null,e.toString());
        
    } 
}//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField exitDate;
    private javax.swing.JTextField exitTime;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField passNumber;
    // End of variables declaration//GEN-END:variables

}
